<?php

namespace AppBundle\Repository;

/**
 * BordereauSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BordereauSalleRepository extends \Doctrine\ORM\EntityRepository
{
}
