<?php

namespace AppBundle\Repository;

/**
 * BordereauRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BordereauRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
