<?php

namespace AppBundle\Repository;

/**
 * DepensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepensesRepository extends \Doctrine\ORM\EntityRepository
{
}
