<?php

namespace AppBundle\Repository;

/**
 * SemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike( $name)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.titre LIKE :name')
            ->setParameter('name', "%$name%")
            ->orderBy('a.titre')
            ->setMaxResults(10)
            ->getQuery()
            ->execute()
            ;
    }
}
