<?php

namespace AppBundle\Repository;

/**
 * SemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike( $name)
    {
       return $this->createQueryBuilder('f')
            ->where('f.titre LIKE :name')
            ->setParameter('name', '%'.$name.'%')
            ->getQuery()
            ->execute();






    }
}
