<?php

namespace AppBundle\Repository;

/**
 * SeanceRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
