<?php

namespace AppBundle\Repository;

/**
 * SeanceSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceSalleRepository extends \Doctrine\ORM\EntityRepository
{
}
