<?php

namespace AppBundle\Repository;

/**
 * SemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemaineRepository extends \Doctrine\ORM\EntityRepository
{
}
